common/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('', views.main, name='main'),
    path('signup', views.signup, name='signup'),
    path('login', auth_views.LoginView.as_view(template_name='common/main.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('main_pop/', views.main_pop, name='main_pop'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('pybo/', include('pybo.urls')),
]

pybo/urls.py
from django.urls import path
from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.pybo, name='pybo'),
]

common/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator

class User(AbstractUser):
    nickname = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=50, unique=True)
    phoneNumberRegex = RegexValidator(regex=r'^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$')
    phone = models.CharField(validators=[phoneNumberRegex], max_length=11, unique=True)
    first_name = None
    last_name = None

pybo/models.py
from django.db import models
from django.conf import settings

common/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User

class signupForm(UserCreationForm):
    class Meta: #메타 안에 있는 모델과 필드들을 커스텀 유저에 맞게 수정 작업하는 것
        model=User
        fields= ['username', 'password1', 'password2', 'nickname', 'phone', 'email']

pybo/forms.py
from django import forms
from pybo.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        labels = {
            'subject': '제목',
            'content': '내용',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

common/views.py
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from .forms import signupForm

def main(request):
    return render(request, 'common/main.html')

def main_pop(request):
    return render(request, 'common/main_pop.html')

def board(request):
    return render(request, 'pybo/pybo.html')

def signup(request):
    if request.method == "POST":
        form = signupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            auth_login(request, user)  # 로그인
            if user:    # authenticate함수가 사용자 인증 처리를 성공하면 user는 True값 반환
                return redirect('common:main_pop')    # main_pop 함수에서 랜더링하는 페이지가 팝업창 호출하는 기능 가지고 있음!
        else:
            return redirect('common:signup')
    else:
        form = signupForm()
    return render(request, 'common/signup.html', {'form': form})

pybo/views.py
from django.shortcuts import render, redirect

def pybo(request):
    return render(request, 'pybo/pybo.html')

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

from ..models import Question
from django.db.models import Q

def index(request):
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj, 'page': page, 'kw': kw}
    return render(request, 'pybo/question_list.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <title>Autoslider</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</head>
<body>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

templates/common/main.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
</head>
    <body>
        {% extends 'base.html' %}
        {% block content %}
<!-- 로고 -->
        <div id ="logo_div" class="logo">
            <img id="logo_img" src="../static/logo3.png" class="img-fluid">
        </div>

<!-- 아이디, 비밀번호 입력란, 로그인 버튼 -->
        <form action="{% url 'common:login' %}" method="POST">
            {% csrf_token %}
            {% include "form_errors.html" %}
            <div id="id_div" class="input-group mb-3">
                <span id="id_span" class="input-group-text">아이디</span>
                <input type="text" name="username" class="form-control" placeholder="아이디 입력">
            </div>
            <div id="password_div" class="input-group mb-3">
                <span class="input-group-text">비밀번호</span>
                <input type="password"  name="password" class="form-control" placeholder="비밀번호 입력">
            </div>
            <div id="login_div">
                <button id="login_button" type="submit" class="btn btn-success btn-lg">로그인</button>
            </div>
        </form>

<!-- 회원가입 버튼 -->
        {% if user.is_authenticated %}
        {% else %}
        <div id="signup_div">
            <a href="{% url 'common:signup' %}">
                <button id="signup_button" type="submit" class="btn btn-warning btn-lg">회원가입</button>
            </a>
        </div>
        {% endif %}

<!-- 게시판 버튼 -->
        {% if user.is_authenticated %}
        <div id="board_div" class="dropdown">
            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            메뉴
            </a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'pybo:pybo' %}">게시판</a></li>
                <li><a class="dropdown-item" href="#">마이페이지</a></li>
                <li><a class="dropdown-item" href="#">요약페이지</a></li>
            </ul>
        </div>
        {% endif %}

<!-- 푸터 -->
        <br>
        <div id="footer_div">
        <hr>
        <div class="footer_wrap" style="text-align:center;">
            <img src="/static/andlogo.jpg" alt="logoimage">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <B style = "font-size:16px">CONTACT US&nbsp;&nbsp;&nbsp;</B>
            <i class="bi bi-telephone-fill"></i> 전화번호: 02-599-8697 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <i class="bi bi-house-door-fill"></i> 관리자 이메일: autoslider@site.com
        </div>
    <br>
    <p align="center"> Copyright ⓒ2023 And.&nbsp;All Rights Reserved. </p>
        </div>
        {% endblock %}
</body>
</html>

templates/common/main_pop.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
</head>
    <body>
        {% extends 'base.html' %}
        {% block content %}
<!-- 로고 -->
        <div id ="logo_div" class="logo">
            <img id="logo_img" src="../../static/logo3.png" class="img-fluid">
        </div>

<!-- 아이디, 비밀번호 입력란, 로그인 버튼 -->
        <form action="{% url 'common:login' %}" method="POST">
            {% csrf_token %}
            {% include "form_errors.html" %}
            <div id="id_div" class="input-group mb-3">
                <span id="id_span" class="input-group-text">아이디</span>
                <input type="text" name="username" class="form-control" placeholder="아이디 입력">
            </div>
            <div id="password_div" class="input-group mb-3">
                <span class="input-group-text">비밀번호</span>
                <input type="password"  name="password" class="form-control" placeholder="비밀번호 입력">
            </div>
            <div id="login_div">
                <button id="login_button" type="submit" class="btn btn-success btn-lg">로그인</button>
            </div>
        </form>

<!-- 회원가입 버튼 -->
        {% if user.is_authenticated %}
        {% else %}
        <div id="signup_div">
            <a href="{% url 'common:signup' %}">
                <button id="signup_button" type="submit" class="btn btn-warning btn-lg">회원가입</button>
            </a>
        </div>
        {% endif %}

<!-- 게시판 버튼 -->
        {% if user.is_authenticated %}
        <div id="board_div" class="dropdown">
            <a class="btn btn-warning dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            메뉴
            </a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'pybo:pybo' %}">게시판</a></li>
                <li><a class="dropdown-item" href="#">마이페이지</a></li>
                <li><a class="dropdown-item" href="#">요약페이지</a></li>
            </ul>
        </div>
        {% endif %}

<!-- 푸터 -->
        <div id="footer_div">
        <hr>
        <div id="footer_font">
            <img src="/static/andlogo.jpg" alt="logoimage">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <B style = "font-size:16px">CONTACT US&nbsp;&nbsp;&nbsp;</B>
            <i class="bi bi-telephone-fill"></i> 전화번호: 02-599-8697 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <i class="bi bi-house-door-fill"></i> 관리자 이메일: autoslider@site.com
        </div>
    <br>
    <p id="footer_Copyright">Copyright ⓒ2023 And.&nbsp;All Rights Reserved.</p>
        </div>

<!-- JavaScript 코드 -->
<!-- SweetAlert2 라이브러리를 불러옵니다. -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

<!-- 회원가입 완료 후 실행할 코드입니다. -->
<script>
    Swal.fire(
      '환영합니다!',
      '회원가입이 완료 되었습니다!',
      'success'
    );
</script>
        {% endblock %}
</body>
</html>

templates/common/signup.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>AutoSlider</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
          crossorigin="anonymous">
    <link href="https://getbootstrap.com/docs/5.2/assets/css/docs.css" rel="stylesheet">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
</head>
<body class="p-3 m-0 border-0 bd-example">
    <form method="post" action="{% url 'common:signup' %}" class=" needs-validation was-validated" novalidate="">
        {% csrf_token %}

         <!-- Example Code -->
         <div class="container-fluid d-flex justify-content-center align-items-center" style="height:100vh;">
         <div class="row d-flex justify-content-center align-items-center">
            <!-- 이미지에 대한 정보 -->
            <div class="col-md-4 text-center" >
            <img src="../../static/logo3.png">
            </div>
            <br>
            <!-- 필수 정보 입력 줄 -->
                <br>
                <center> 필수정보 입력 </center>
                <h4 class ="mb-3"></h4>
                <div class="col-md-12 text-center">
                </div>
            <!-- 아이디에 대한 정보 --><h4 class ="mb-3"></h4>
            <div class="col-md-4" >
                <label for="username" class="form-label">아이디</label>
                <input type="text" class="form-control is-valid" name="username" id="username" placeholder="아이디 입력"  required="">
                <div class="valid-feedback"></div>
            </div >
            <!-- 비밀번호에 대한 정보 --><h4 class ="mb-3"></h4>
                <div class="col-md-4" >
                <label for="password1" class="form-label">비밀번호</label>
                <input type="password" class="form-control is-valid" name="password1" id="password1" placeholder="비밀번호 입력"  required="">
                <div class="valid-feedback"></div>
            </div>
            <!-- 비밀번호 확인에 대한 정보 --><h4 class ="mb-3"></h4>
            <div class="col-md-4" >
            <label for="password2" class="form-label">비밀번호 확인</label>
            <input type="password" class="form-control is-valid" name="password2" id="password2" placeholder="비밀번호 확인"  required="">
            <div class="valid-feedback"></div>
            </div>
            <!-- 이메일에 대한 정보 --><h4 class ="mb-3"></h4>
            <div class="col-md-4" >
            <label for="email">이메일</label>
            <div class="input-group mb-3">
            <input type="text" class="form-control is-valid" name="email" id="email" placeholder="이메일 입력" required>
            <select class="box" id="domain-list">
            <option value="type">직접 입력</option>
            <option value="naver.com">naver.com</option>
            <option value="daum.net">daum.net</option>
            <option value="google.com">google.com</option>
            <option value="nate.com">nate.com</option>
            <option value="kakao.com">kakao.com</option>
            </select>
            </div>
            </div>
            <!-- 닉네임(별명)에 대한 정보 --><h4 class ="mb-3"></h4>
            <div class="col-md-4" >
            <label for="nickname" class="form-label">닉네임(별명)</label>
            <input type="text" class="form-control is-valid" name="nickname" id="nickname" placeholder="닉네임(별명) 입력" required>
            <div class="valid-feedback"></div>
            </div>
            <!-- 전화번호에 대한 정보 --><h4 class ="mb-3"></h4>
            <div class="col-md-4" >
            <label for="phone" class="form-label">전화번호</label>
            <input type="text" class="form-control is-valid" name="phone" id="phone" placeholder="전화번호 입력" required>
            <div class="valid-feedback"></div>
            </div>
            <h4 class ="mb-3"></h4>
            <div class="col-md-12 text-center" >
                <script src="../../static/test.js"></script>
            <button type="submit" class="btn btn-success btn-block" id="signup-button"> 확인</button>
            <button type="submit" class="btn btn-danger btn-block"> 취소</button>
            </div>
         </div>
         </div>
         <!-- 푸터 -->
        <br>
        <div id="footer_div">
        <hr>
        <div class="footer_wrap" style="text-align:center;">
            <img src="/static/andlogo.jpg" alt="logoimage">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <B style = "font-size:16px">CONTACT US&nbsp;&nbsp;&nbsp;</B>
            <i class="bi bi-telephone-fill"></i> 전화번호: 02-599-8697 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <i class="bi bi-house-door-fill"></i> 관리자 이메일: autoslider@site.com
        </div>
    <br>
    <p align="center"> Copyright ⓒ2023 And.&nbsp;All Rights Reserved. </p>
        </div>
         <!-- End Example Code -->
    </form>
</body>
</html>